### ISSUE TITLE
SUGGESTION: Publishing the app in the Google Play Store

### ISSUE THREAD

**Issue by Dimasua** [Klettner/MM-Remote#12]
Hi, you did a great work with the app. Thank you. Would that be possible to publish the MM-Remote in the Google Play Store?

**Comment by Klettner** [comment]
Hi Dimasua, thanks for all of your feedback. I appreciate it.
Currently there are no plans to publish it to the Google Play Store but I will think about it.

The downsides of publishing it there are:
- I would need to create (and pay for) a Google Developer account
- I would need to set up and maintain the listing in the Play Store in addition to Github, which means quite some extra work

The main upsides would be:
- Easier way to download updates for the users
- A trusted platform to download the app

I will let you know once I came up with a decision.

I also thought about creating and releasing an IOS version of the app, which would require me to pay for an Apple Developer account (around 99 US-Dollars per year). Therefore I would need to sell the app for a small fee (e.g. 1.50€), but I'm not sure if anyone would be willing to pay for that. Let me know what you think.
