### ISSUE TITLE
MMM-BackgroundSlideshow does not respond to the MM-Remote Stop/Play

### ISSUE THREAD

**Issue by Dimasua** [Klettner/MM-Remote#13]
Hi, I configured all dependencies, and can control the MM with the MM-Remote. 
The MMM-BackgroundSlideshow I put on a second page of the MM. However only one control function is working - forward. 
Stop and Play doesn't respond. So it refreshes the images in a loop and I can't neither stop nor paused it from the MM-Remote.

**Comment by Klettner** [comment]
Hi, I just checked it with my set up and indeed there seems to be a problem. I will look into that.

**Comment by Klettner** [comment]
I found the bug and fixed it. It seem like MMM-BackgroundSlideshow changed the notification for stopping the slideshow.

Could you check if this version fixes your problems. You simply have to unzip the apk and download + install it to your phone.
Once I know that it fixes your issues, I will create a new release for everyone.
[app-release-v3.0.2.zip](https://github.com/Klettner/MM-Remote/files/6433315/app-release-v3.0.2.zip)
