### ISSUE TITLE
Slider for Volume?

### ISSUE THREAD

**Issue by dresch27** [Klettner/MM-Remote#15]
This is a feature request. Is there any way to create a slider for volume?

**Comment by Klettner** [comment]
Thanks for your suggestion.
I think this is a great idea. I can look into this and include it in one of the future updates.
Do these VOLUME_UP/_DOWN commands work on default or do you use an additional module for this?
If so, it would be great if you could send a link to it.

**Comment by dresch27** [comment]
Thanks! The VOLUME_UP/_DOWN sends a notification with the installed MMM-Volume module and works right out of the box.

**Comment by dresch27** [comment]
Also, would be great if it had a QRI code to port settings over to different phones.

**Comment by Klettner** [comment]
I agree, this would be a nice feature. The problem is that currently all dart QR-scanner packages have only support for android and ios, but I would like to maintain one codebase for all platforms (Android, Windows, Linux). Since Windows and Linux support is relatively new, we probably just need to wait some time, until they are supported by these packages as well.

**Comment by dresch27** [comment]
Completely understandable and thank you for the explanation. 
Separately, my internet went out recently and reset the IP address for my Pi. Is there any way to edit each "Device" IP address in the app? Thanks!

**Comment by Klettner** [comment]
Unfortunately this is not possible at the moment, but definitively something that should be added in the future

**Comment by Klettner** [comment]
I added a separate issue for this

**Comment by Dresch360** [comment]
I figured out a very simple solution for the QR code issue for downloading the app to an android phone.
- Install an image module - I installed MMM-SimpleLogo
- Go to  https://www.qr-code-generator.com/   to create a free QR code and you can create as many as you like.
- Enter the link for latest release of your apk in the QR generator: https://github.com/Klettner/MM-Remote/releases/download/v3.1.0/app-release.apk
- Rename and place your QR code image in the image folder of your image module (in my case for simplelogo it's in "Public") and update the image module with the correct image file path and name. 
- Voila!

**Comment by Klettner** [comment]
I think it is also a good idea to add a QR code to the MM-Remote Github page, so that it is easier to download the app on the smartphone when visiting the Github page with a pc
