### ISSUE TITLE
Increase size of overlay for Monitor Brightness?

### ISSUE THREAD

**Issue by Dresch360** [Klettner/MM-Remote#18]
Thanks for adding the volume control - it works great!

I notice a small issue with the monitor brightness overlay. The overlay is not covering the entire screen and leaving a portion (100px top and left) exposed. Is there a way to make the overlay larger?

Thanks again for a great module!! Super useful.

**Comment by Klettner** [comment]
You're welcome :)

Changing the monitor brightness was not implemented by me, it is part of the separate  module [MMM-Remote-Control](https://github.com/Jopyth/MMM-Remote-Control), I'm just using their API endpoint. You need to ask there if you want this to be changed, sorry.

**Comment by Dresch360** [comment]
Thanks. I figured this one out. 
In the MMM-Remote-Control folder, in the remote-control.css file, I change the height to 120% and added   margin-top: -50px; and this fixed it. 

In addition, the Remote Control brightness overlay was preventing all touch capabilities on screen, so I changed "z-index: 2;" to "z-index: 1;"

#remote-control-overlay {
  position: fixed;
  z-index: 1;
  background-color: rgba(0,0,0,0.1);
  width: 100%;
  height: 120%;
  margin-top: -50px;
}

**Comment by Klettner** [comment]
Thanks for sharing, this works great. I will add it to the Troubleshooting section of the wiki.  👍

I don't know if it is depending on the screen size, but I needed to do the same for width and margin-left.
