### ISSUE TITLE
Possible to add "Refresh mirror" to the main menu under "Shutdown mirror?"

### ISSUE THREAD

**Issue by Dresch360** [Klettner/MM-Remote#19]
Thanks again! - looks like the API calls aren't working well and would be great to add this to the main menu under "Shutdown Mirror". Is this possible? 

http://localhost:8080/remote?action=REFRESH

**Comment by Klettner** [comment]
Could you try to explain what's not working with the API calls? Maybe you can have a look at [wiki/custom-commands](https://github.com/Klettner/MM-Remote/wiki/Custom-Commands) to see how to use it. I had no issues with it so far. 

Sure, I can add this. This shouldn't be too much effort

**Comment by Dresch360** [comment]
Thanks for your reply! Sure, every time I do any type of API call, I receive "Cannot Get...." - i.e. http://192.168.x.xx:8080/smartmirror/refresh
I get: "Cannot GET /smart/refresh"

**Comment by Klettner** [comment]
Make sure your Mirror and MMM-Remote-Control are running the current version.   

If you want to invoke a refresh from outside of the App you can use: ``http://<your_ip-Address>:<your_port>/api/refresh`` you might also need to include your api key in the header of the request e.g ``"Authorization: "apiKey <your_API_key>"`` (And don't forget to change <your_ip-Address>, <your_port> and <your_API_key> to your specific values).   

To create a refresh custom command in the app: 
* Click on the + in the custom commands tab
* specify a command name e.g. ``refresh mirror``
* specify the notification, here ``/refresh``
* payload should be empty
* click on create and everything should work

I hope that helps
