### ISSUE TITLE
Remote Control Integration

### ISSUE THREAD

**Issue by ezeholz** [Klettner/MM-Remote#5]
Hello! Ezequiel here. I'm the actual collaborator of [MMM-Remote-Control](https://github.com/Jopyth/MMM-Remote-Control).
I'm reaching you because I like this integration of our module with your application, and I was wonder, are you still maintain this app? I would be glad to add your repo inside the Readme of the Remote Control if you're still maintaining this.

Also, just a friendly reminder, the remote endpoint would be deprecated soon. I can PR the changes myself if you're too busy, but I really don't know Dart. [This](https://github.com/Klettner/MM-Remote/blob/master/lib/services/httpRest.dart) file should be modified, right?

Great app! Hope you're doing great.
Cheers :D

**Comment by Klettner** [comment]
Hello Ezequiel, thanks for your intrest in the project. 
Yes, this app is still maintained so feel free to add it to your Readme.

Thanks for the info about the remote endpoint. I have already looked into the new API yesterday and it looks promising. I'm probably going to update the app in the next couple of days.

Keep up the good work with MMM-Remote-Control and stay healthy :)
